### ISSUE TITLE
SMS broken after jitterbuffer rework

### ISSUE THREAD

**Issue by stefansaraev** [g4klx/MMDVMHost#370]
Hi Jonathan

It seems that SMS from brandmeister got completely broken ( at least for me :) ) after 526e2c4

Log from MMDVMHost 51e0bf0 (before jitterbuffer commit) + DMRGatway ad70ea8 : http://ix.io/E2r
Log from MMDVMHost 526e2c4 (after jitterbuffer commit) + DMRGatway ad70ea8 : http://ix.io/E2t

before 526e2c4 - sms from brandmeister is received on the radio
after 526e2c4 - sms from brandmeister not received, few missed private calls received instead

MMDVMhost configuration: http://ix.io/E2u
DMRGateway configuration: http://ix.io/E2x
^ irrelevant parts of the config files are removed from those pastes.

testing with tyt md380 and mmdvm hs hotspot. let me know if you want more logs with specific loglevel / debug enabled.

**Comment by g4klx** [comment]
Hi Stefan
I think I've found an issue with the way that the MMDVM populates the sequence number when sending data transmissions to the network. I hope I have fixed this now, the data sent to the network should now be correct, hopefully it'll be sent through the network correctly, if so, it should appear correctly at the receiving end.
Jonathan  G4KLX

**Comment by stefansaraev** [comment]
well, that was fast. a3155c1 fixed the issue. thanks Jonathan!

**Comment by stefansaraev** [comment]
argh. wrong binary was tested. sorry about that. nope  a3155c1 didn't fix the issue :(

**Comment by g4klx** [comment]
We need to get some tracing working then. If the end sending the data to you is broken then my fix won't work.

**Comment by pjao** [comment]
Here it goes a dump:

M: 2018-01-11 22:12:44.316 Preamble CSBK
M: 2018-01-11 22:12:44.316 0000:  BD 00 80 0D 04 03 52 28 EC AF C2 D8                *......R(....*
M: 2018-01-11 22:12:44.317 DMR Slot 2, received RF Data Preamble CSBK (13 to follow) from CT2JAY to 262994
M: 2018-01-11 22:12:44.376 Preamble CSBK
M: 2018-01-11 22:12:44.376 0000:  BD 00 80 0C 04 03 52 28 EC AF 7A B9                *......R(..z.*
M: 2018-01-11 22:12:44.377 DMR Slot 2, received RF Data Preamble CSBK (12 to follow) from CT2JAY to 262994
M: 2018-01-11 22:12:44.438 Preamble CSBK
M: 2018-01-11 22:12:44.439 0000:  BD 00 80 0B 04 03 52 28 EC AF 63 FD                *......R(..c.*
M: 2018-01-11 22:12:44.439 DMR Slot 2, received RF Data Preamble CSBK (11 to follow) from CT2JAY to 262994
M: 2018-01-11 22:12:44.496 Preamble CSBK
M: 2018-01-11 22:12:44.496 0000:  BD 00 80 0A 04 03 52 28 EC AF DB 9C                *......R(....*
M: 2018-01-11 22:12:44.497 DMR Slot 2, received RF Data Preamble CSBK (10 to follow) from CT2JAY to 262994
M: 2018-01-11 22:12:44.558 Preamble CSBK
M: 2018-01-11 22:12:44.559 0000:  BD 00 80 09 04 03 52 28 EC AF 03 1E                *......R(....*
M: 2018-01-11 22:12:44.559 DMR Slot 2, received RF Data Preamble CSBK (9 to follow) from CT2JAY to 262994
M: 2018-01-11 22:12:44.616 Preamble CSBK
M: 2018-01-11 22:12:44.616 0000:  BD 00 80 08 04 03 52 28 EC AF BB 7F                *......R(....*
M: 2018-01-11 22:12:44.617 DMR Slot 2, received RF Data Preamble CSBK (8 to follow) from CT2JAY to 262994
M: 2018-01-11 22:12:44.678 Preamble CSBK
M: 2018-01-11 22:12:44.678 0000:  BD 00 80 07 04 03 52 28 EC AF 31 96                *......R(..1.*
M: 2018-01-11 22:12:44.679 DMR Slot 2, received RF Data Preamble CSBK (7 to follow) from CT2JAY to 262994
M: 2018-01-11 22:12:44.736 Preamble CSBK
M: 2018-01-11 22:12:44.736 0000:  BD 00 80 06 04 03 52 28 EC AF 89 F7                *......R(....*
M: 2018-01-11 22:12:44.737 DMR Slot 2, received RF Data Preamble CSBK (6 to follow) from CT2JAY to 262994
M: 2018-01-11 22:12:44.798 Preamble CSBK
M: 2018-01-11 22:12:44.798 0000:  BD 00 80 05 04 03 52 28 EC AF 51 75                *......R(..Qu*
M: 2018-01-11 22:12:44.799 DMR Slot 2, received RF Data Preamble CSBK (5 to follow) from CT2JAY to 262994
M: 2018-01-11 22:12:44.856 DMR, Unconfirmed Data Header
M: 2018-01-11 22:12:44.856 0000:  02 40 04 03 52 28 EC AF 84 00 19 EB                *.@..R(......*
M: 2018-01-11 22:12:44.857 DMR Slot 2, received RF data header from CT2JAY to 262994, 4 blocks
M: 2018-01-11 22:12:45.096 DMR Slot 2, ended RF data transmission
D: 2018-01-11 22:12:45.409 DMR Slot 2, JitterBuffer: starting the timer
D: 2018-01-11 22:12:45.532 DMR Slot 2, JitterBuffer: rejecting duplicate frame with seqNo=0, pos=0, raw=0, head=0, tail=128
M: 2018-01-11 22:12:45.912 Preamble CSBK
M: 2018-01-11 22:12:45.919 0000:  BD 00 80 05 28 EC AF 04 03 52 5A 39                *....(....RZ9*
M: 2018-01-11 22:12:45.919 DMR Slot 2, received network Data Preamble CSBK (5 to follow) from 262994 to CT2JAY
D: 2018-01-11 22:12:46.094 DMR Slot 2, JitterBuffer: no data available, elapsed=182ms, raw=5, head=5
D: 2018-01-11 22:12:46.094 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-11 22:12:46.156 DMR Slot 2, JitterBuffer: no data available, elapsed=244ms, raw=6, head=6
D: 2018-01-11 22:12:46.156 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-11 22:12:46.213 DMR Slot 2, JitterBuffer: no data available, elapsed=301ms, raw=7, head=7
D: 2018-01-11 22:12:46.213 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-11 22:12:46.275 DMR Slot 2, JitterBuffer: no data available, elapsed=363ms, raw=8, head=8
D: 2018-01-11 22:12:46.275 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-11 22:12:46.336 DMR Slot 2, JitterBuffer: no data available, elapsed=424ms, raw=9, head=9
D: 2018-01-11 22:12:46.337 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-11 22:12:46.368 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=0, raw=10, head=10, tail=138
D: 2018-01-11 22:12:46.393 DMR Slot 2, JitterBuffer: no data available, elapsed=481ms, raw=10, head=10
D: 2018-01-11 22:12:46.394 DMR Slot 2, JitterBuffer: returning the last received frame
M: 2018-01-11 22:12:46.394 DMR Slot 2, received network late entry from 262994 to CT2JAY
D: 2018-01-11 22:12:46.430 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=0, raw=11, head=11, tail=139
D: 2018-01-11 22:12:46.456 DMR Slot 2, JitterBuffer: no data available, elapsed=544ms, raw=11, head=11
D: 2018-01-11 22:12:46.456 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-11 22:12:46.513 DMR Slot 2, JitterBuffer: no data available, elapsed=601ms, raw=12, head=12
D: 2018-01-11 22:12:46.513 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-11 22:12:46.513 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=1, raw=13, head=13, tail=141
D: 2018-01-11 22:12:46.575 DMR Slot 2, JitterBuffer: no data available, elapsed=663ms, raw=13, head=13
D: 2018-01-11 22:12:46.575 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-11 22:12:46.580 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=2, raw=14, head=14, tail=142
D: 2018-01-11 22:12:46.632 DMR Slot 2, JitterBuffer: no data available, elapsed=720ms, raw=14, head=14
D: 2018-01-11 22:12:46.632 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-11 22:12:46.694 DMR Slot 2, JitterBuffer: no data available, elapsed=782ms, raw=15, head=15
D: 2018-01-11 22:12:46.694 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-11 22:12:46.704 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=3, raw=16, head=16, tail=144
D: 2018-01-11 22:12:46.715 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=4, raw=16, head=16, tail=144
D: 2018-01-11 22:12:46.756 DMR Slot 2, JitterBuffer: no data available, elapsed=844ms, raw=16, head=16
D: 2018-01-11 22:12:46.756 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-11 22:12:46.767 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=5, raw=17, head=17, tail=145
D: 2018-01-11 22:12:46.813 DMR Slot 2, JitterBuffer: no data available, elapsed=901ms, raw=17, head=17
D: 2018-01-11 22:12:46.813 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-11 22:12:46.824 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=6, raw=18, head=18, tail=146
D: 2018-01-11 22:12:46.875 DMR Slot 2, JitterBuffer: no data available, elapsed=963ms, raw=18, head=18
D: 2018-01-11 22:12:46.875 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-11 22:12:46.932 DMR Slot 2, JitterBuffer: no data available, elapsed=1020ms, raw=19, head=19
D: 2018-01-11 22:12:46.932 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-11 22:12:46.948 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=7, raw=20, head=20, tail=148
D: 2018-01-11 22:12:46.958 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=8, raw=20, head=20, tail=148
D: 2018-01-11 22:12:46.994 DMR Slot 2, JitterBuffer: no data available, elapsed=1082ms, raw=20, head=20
D: 2018-01-11 22:12:46.994 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-11 22:12:47.010 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=9, raw=21, head=21, tail=149
D: 2018-01-11 22:12:47.056 DMR Slot 2, JitterBuffer: no data available, elapsed=1144ms, raw=21, head=21
D: 2018-01-11 22:12:47.056 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-11 22:12:47.108 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=10, raw=22, head=22, tail=150
D: 2018-01-11 22:12:47.113 DMR Slot 2, JitterBuffer: no data available, elapsed=1201ms, raw=22, head=22
D: 2018-01-11 22:12:47.113 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-11 22:12:47.119 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=11, raw=23, head=23, tail=151
D: 2018-01-11 22:12:47.175 DMR Slot 2, JitterBuffer: no data available, elapsed=1263ms, raw=23, head=23
D: 2018-01-11 22:12:47.176 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-11 22:12:47.191 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=12, raw=24, head=24, tail=152
D: 2018-01-11 22:12:47.232 DMR Slot 2, JitterBuffer: no data available, elapsed=1320ms, raw=24, head=24
D: 2018-01-11 22:12:47.232 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-11 22:12:47.243 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=13, raw=25, head=25, tail=153
D: 2018-01-11 22:12:47.294 DMR Slot 2, JitterBuffer: no data available, elapsed=1382ms, raw=25, head=25
D: 2018-01-11 22:12:47.295 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-11 22:12:47.300 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=14, raw=26, head=26, tail=154
D: 2018-01-11 22:12:47.356 DMR Slot 2, JitterBuffer: no data available, elapsed=1444ms, raw=26, head=26
D: 2018-01-11 22:12:47.357 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-11 22:12:47.362 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=15, raw=27, head=27, tail=155
D: 2018-01-11 22:12:47.413 DMR Slot 2, JitterBuffer: no data available, elapsed=1501ms, raw=27, head=27
D: 2018-01-11 22:12:47.414 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-11 22:12:47.424 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=16, raw=28, head=28, tail=156
D: 2018-01-11 22:12:47.476 DMR Slot 2, JitterBuffer: no data available, elapsed=1564ms, raw=28, head=28
D: 2018-01-11 22:12:47.476 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-11 22:12:47.481 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=17, raw=29, head=29, tail=157
D: 2018-01-11 22:12:47.533 DMR Slot 2, JitterBuffer: no data available, elapsed=1621ms, raw=29, head=29
D: 2018-01-11 22:12:47.533 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-11 22:12:47.543 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=18, raw=30, head=30, tail=158
D: 2018-01-11 22:12:47.595 DMR Slot 2, JitterBuffer: no data available, elapsed=1683ms, raw=30, head=30
D: 2018-01-11 22:12:47.595 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-11 22:12:47.657 DMR Slot 2, JitterBuffer: no data available, elapsed=1745ms, raw=31, head=31
D: 2018-01-11 22:12:47.657 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-11 22:12:47.677 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=19, raw=32, head=32, tail=160
D: 2018-01-11 22:12:47.688 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=20, raw=32, head=32, tail=160
D: 2018-01-11 22:12:47.704 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=21, raw=32, head=32, tail=160
D: 2018-01-11 22:12:47.714 DMR Slot 2, JitterBuffer: no data available, elapsed=1802ms, raw=32, head=32
D: 2018-01-11 22:12:47.714 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-11 22:12:47.776 DMR Slot 2, JitterBuffer: no data available, elapsed=1864ms, raw=33, head=33
D: 2018-01-11 22:12:47.776 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-11 22:12:47.786 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=22, raw=34, head=34, tail=162
D: 2018-01-11 22:12:47.833 DMR Slot 2, JitterBuffer: no data available, elapsed=1921ms, raw=34, head=34
D: 2018-01-11 22:12:47.833 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-11 22:12:47.849 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=23, raw=35, head=35, tail=163
M: 2018-01-11 22:12:47.890 DMR Slot 2, network watchdog has expired, 1.6 seconds, 96% packet loss, BER: 0.0%
D: 2018-01-11 22:12:47.911 DMR Slot 2, JitterBuffer: starting the timer
D: 2018-01-11 22:12:48.414 DMR Slot 2, JitterBuffer: no data available, elapsed=0ms, raw=0, head=0
D: 2018-01-11 22:12:48.419 DMR Slot 2, JitterBuffer: no data available, elapsed=5ms, raw=1, head=1
D: 2018-01-11 22:12:48.419 DMR Slot 2, JitterBuffer: no data available, elapsed=5ms, raw=2, head=2
D: 2018-01-11 22:12:48.476 DMR Slot 2, JitterBuffer: no data available, elapsed=62ms, raw=3, head=3
D: 2018-01-11 22:12:48.537 DMR Slot 2, JitterBuffer: no data available, elapsed=123ms, raw=4, head=4
D: 2018-01-11 22:12:48.594 DMR Slot 2, JitterBuffer: no data available, elapsed=180ms, raw=5, head=5
D: 2018-01-11 22:12:48.656 DMR Slot 2, JitterBuffer: no data available, elapsed=242ms, raw=6, head=6
D: 2018-01-11 22:12:48.717 DMR Slot 2, JitterBuffer: no data available, elapsed=303ms, raw=7, head=7
D: 2018-01-11 22:12:48.774 DMR Slot 2, JitterBuffer: no data available, elapsed=360ms, raw=8, head=8
D: 2018-01-11 22:12:48.836 DMR Slot 2, JitterBuffer: no data available, elapsed=422ms, raw=9, head=9
D: 2018-01-11 22:12:48.898 DMR Slot 2, JitterBuffer: no data available, elapsed=484ms, raw=10, head=10
D: 2018-01-11 22:12:48.954 DMR Slot 2, JitterBuffer: no data available, elapsed=540ms, raw=11, head=11
D: 2018-01-11 22:12:49.016 DMR Slot 2, JitterBuffer: no data available, elapsed=602ms, raw=12, head=12
D: 2018-01-11 22:12:49.078 DMR Slot 2, JitterBuffer: no data available, elapsed=664ms, raw=13, head=13
D: 2018-01-11 22:12:49.135 DMR Slot 2, JitterBuffer: no data available, elapsed=721ms, raw=14, head=14
D: 2018-01-11 22:12:49.196 DMR Slot 2, JitterBuffer: no data available, elapsed=782ms, raw=15, head=15
D: 2018-01-11 22:12:49.258 DMR Slot 2, JitterBuffer: no data available, elapsed=844ms, raw=16, head=16
D: 2018-01-11 22:12:49.315 DMR Slot 2, JitterBuffer: no data available, elapsed=901ms, raw=17, head=17
D: 2018-01-11 22:12:49.377 DMR Slot 2, JitterBuffer: no data available, elapsed=963ms, raw=18, head=18
D: 2018-01-11 22:12:49.438 DMR Slot 2, JitterBuffer: no data available, elapsed=1024ms, raw=19, head=19
D: 2018-01-11 22:12:49.495 DMR Slot 2, JitterBuffer: no data available, elapsed=1081ms, raw=20, head=20
D: 2018-01-11 22:12:49.557 DMR Slot 2, JitterBuffer: no data available, elapsed=1143ms, raw=21, head=21
D: 2018-01-11 22:12:49.614 DMR Slot 2, JitterBuffer: no data available, elapsed=1200ms, raw=22, head=22
D: 2018-01-11 22:12:49.675 DMR Slot 2, JitterBuffer: no data available, elapsed=1261ms, raw=23, head=23
D: 2018-01-11 22:12:51.479 DMR Slot 2, JitterBuffer: no data available, elapsed=3065ms, raw=53, head=53
D: 2018-01-11 22:12:51.479 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-11 22:12:51.535 DMR Slot 2, JitterBuffer: no data available, elapsed=3121ms, raw=54, head=54
D: 2018-01-11 22:12:51.536 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-11 22:12:51.597 DMR Slot 2, JitterBuffer: no data available, elapsed=3183ms, raw=55, head=55
D: 2018-01-11 22:12:51.598 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-11 22:12:51.654 DMR Slot 2, JitterBuffer: no data available, elapsed=3240ms, raw=56, head=56
D: 2018-01-11 22:12:51.654 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-11 22:12:51.716 DMR Slot 2, JitterBuffer: no data available, elapsed=3302ms, raw=57, head=57
D: 2018-01-11 22:12:51.716 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-11 22:12:51.778 DMR Slot 2, JitterBuffer: no data available, elapsed=3364ms, raw=58, head=58
D: 2018-01-11 22:12:51.778 DMR Slot 2, JitterBuffer: returning the last received frame
M: 2018-01-11 22:12:51.779 DMR Slot 2, received network late entry from 262994 to CT2JAY
D: 2018-01-11 22:12:51.836 DMR Slot 2, JitterBuffer: no data available, elapsed=3422ms, raw=59, head=59
D: 2018-01-11 22:12:51.836 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-11 22:12:51.898 DMR Slot 2, JitterBuffer: no data available, elapsed=3484ms, raw=60, head=60
D: 2018-01-11 22:12:51.898 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-11 22:12:51.954 DMR Slot 2, JitterBuffer: no data available, elapsed=3540ms, raw=61, head=61
D: 2018-01-11 22:12:51.955 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-11 22:12:52.016 DMR Slot 2, JitterBuffer: no data available, elapsed=3602ms, raw=62, head=62
D: 2018-01-11 22:12:52.017 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-11 22:12:52.078 DMR Slot 2, JitterBuffer: no data available, elapsed=3664ms, raw=63, head=63
D: 2018-01-11 22:12:52.079 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-11 22:12:52.135 DMR Slot 2, JitterBuffer: no data available, elapsed=3721ms, raw=64, head=64
D: 2018-01-11 22:12:52.135 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-11 22:12:52.197 DMR Slot 2, JitterBuffer: no data available, elapsed=3783ms, raw=65, head=65
D: 2018-01-11 22:12:52.197 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-11 22:12:52.254 DMR Slot 2, JitterBuffer: no data available, elapsed=3840ms, raw=66, head=66
D: 2018-01-11 22:12:52.254 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-11 22:12:52.316 DMR Slot 2, JitterBuffer: no data available, elapsed=3902ms, raw=67, head=67
D: 2018-01-11 22:12:52.316 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-11 22:12:52.378 DMR Slot 2, JitterBuffer: no data available, elapsed=3964ms, raw=68, head=68
D: 2018-01-11 22:12:52.378 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-11 22:12:52.435 DMR Slot 2, JitterBuffer: no data available, elapsed=4021ms, raw=69, head=69
D: 2018-01-11 22:12:52.435 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-11 22:12:52.497 DMR Slot 2, JitterBuffer: no data available, elapsed=4083ms, raw=70, head=70
D: 2018-01-11 22:12:52.497 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-11 22:12:52.554 DMR Slot 2, JitterBuffer: no data available, elapsed=4140ms, raw=71, head=71
D: 2018-01-11 22:12:52.554 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-11 22:12:52.616 DMR Slot 2, JitterBuffer: no data available, elapsed=4202ms, raw=72, head=72
D: 2018-01-11 22:12:52.616 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-11 22:12:52.678 DMR Slot 2, JitterBuffer: no data available, elapsed=4264ms, raw=73, head=73
D: 2018-01-11 22:12:52.678 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-11 22:12:52.734 DMR Slot 2, JitterBuffer: no data available, elapsed=4320ms, raw=74, head=74
D: 2018-01-11 22:12:52.735 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-11 22:12:52.796 DMR Slot 2, JitterBuffer: no data available, elapsed=4382ms, raw=75, head=75
D: 2018-01-11 22:12:52.796 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-11 22:12:52.858 DMR Slot 2, JitterBuffer: no data available, elapsed=4444ms, raw=76, head=76
D: 2018-01-11 22:12:52.859 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-11 22:12:52.915 DMR Slot 2, JitterBuffer: no data available, elapsed=4501ms, raw=77, head=77
D: 2018-01-11 22:12:52.916 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-11 22:12:52.977 DMR Slot 2, JitterBuffer: no data available, elapsed=4563ms, raw=78, head=78
D: 2018-01-11 22:12:52.977 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-11 22:12:53.034 DMR Slot 2, JitterBuffer: no data available, elapsed=4620ms, raw=79, head=79
D: 2018-01-11 22:12:53.034 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-11 22:12:53.096 DMR Slot 2, JitterBuffer: no data available, elapsed=4682ms, raw=80, head=80
D: 2018-01-11 22:12:53.096 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-11 22:12:53.158 DMR Slot 2, JitterBuffer: no data available, elapsed=4744ms, raw=81, head=81
D: 2018-01-11 22:12:53.158 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-11 22:12:53.215 DMR Slot 2, JitterBuffer: no data available, elapsed=4801ms, raw=82, head=82
D: 2018-01-11 22:12:53.215 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-11 22:12:53.277 DMR Slot 2, JitterBuffer: no data available, elapsed=4863ms, raw=83, head=83
D: 2018-01-11 22:12:53.277 DMR Slot 2, JitterBuffer: returning the last received frame
M: 2018-01-11 22:12:53.277 DMR Slot 2, network watchdog has expired, 1.6 seconds, 96% packet loss, BER: 0.0%

**Comment by pjao** [comment]
@g4klx Send is OK now, but needs a fix to receive.

M: 2018-01-15 21:45:10.261 Preamble CSBK
M: 2018-01-15 21:45:10.261 0000:  BD 00 80 05 28 EC AF 04 03 51 6A 5A                *....(....QjZ*
M: 2018-01-15 21:45:10.269 DMR Slot 2, received network Data Preamble CSBK (5 to follow) from 262993 to CT2JAY
M: 2018-01-15 21:45:10.275 DMR, Unconfirmed Data Header
M: 2018-01-15 21:45:10.276 0000:  02 4B 28 EC AF 04 03 51 84 00 11 B2                *.K(....Q....*
M: 2018-01-15 21:45:10.276 DMR Slot 2, received network data header from 262993 to CT2JAY, 4 blocks
M: 2018-01-15 21:45:10.441 DMR Slot 2, ended network data transmission
D: 2018-01-15 21:45:11.737 DMR Slot 2, JitterBuffer: starting the timer from append
M: 2018-01-15 21:45:12.241 Preamble CSBK
M: 2018-01-15 21:45:12.241 0000:  BD 00 80 11 28 EC AF 04 03 51 9C E7                *....(....Q..*
M: 2018-01-15 21:45:12.241 DMR Slot 2, received network Data Preamble CSBK (17 to follow) from 262993 to CT2JAY
M: 2018-01-15 21:45:12.246 DMR, Unconfirmed Data Header
M: 2018-01-15 21:45:12.247 0000:  02 48 28 EC AF 04 03 51 90 00 F3 41                *.H(....Q...A*
M: 2018-01-15 21:45:12.247 DMR Slot 2, received network data header from 262993 to CT2JAY, 16 blocks
D: 2018-01-15 21:45:13.143 DMR Slot 2, JitterBuffer: no data available, elapsed=902ms, raw=17, head=17
D: 2018-01-15 21:45:13.143 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-15 21:45:13.205 DMR Slot 2, JitterBuffer: no data available, elapsed=964ms, raw=18, head=18
D: 2018-01-15 21:45:13.205 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-15 21:45:13.261 DMR Slot 2, JitterBuffer: no data available, elapsed=1020ms, raw=19, head=19
D: 2018-01-15 21:45:13.262 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-15 21:45:13.323 DMR Slot 2, JitterBuffer: no data available, elapsed=1082ms, raw=20, head=20
D: 2018-01-15 21:45:13.323 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-15 21:45:13.385 DMR Slot 2, JitterBuffer: no data available, elapsed=1144ms, raw=21, head=21
D: 2018-01-15 21:45:13.385 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-15 21:45:13.442 DMR Slot 2, JitterBuffer: no data available, elapsed=1201ms, raw=22, head=22
D: 2018-01-15 21:45:13.442 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-15 21:45:13.504 DMR Slot 2, JitterBuffer: no data available, elapsed=1263ms, raw=23, head=23
D: 2018-01-15 21:45:13.504 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-15 21:45:13.561 DMR Slot 2, JitterBuffer: no data available, elapsed=1320ms, raw=24, head=24
D: 2018-01-15 21:45:13.561 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-15 21:45:13.622 DMR Slot 2, JitterBuffer: no data available, elapsed=1381ms, raw=25, head=25
D: 2018-01-15 21:45:13.622 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-15 21:45:13.684 DMR Slot 2, JitterBuffer: no data available, elapsed=1443ms, raw=26, head=26
D: 2018-01-15 21:45:13.684 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-15 21:45:13.745 DMR Slot 2, JitterBuffer: no data available, elapsed=1504ms, raw=27, head=27
D: 2018-01-15 21:45:13.745 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-15 21:45:13.801 DMR Slot 2, JitterBuffer: no data available, elapsed=1560ms, raw=28, head=28
D: 2018-01-15 21:45:13.801 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-15 21:45:13.863 DMR Slot 2, JitterBuffer: no data available, elapsed=1622ms, raw=29, head=29
D: 2018-01-15 21:45:13.863 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-15 21:45:13.925 DMR Slot 2, JitterBuffer: no data available, elapsed=1684ms, raw=30, head=30
D: 2018-01-15 21:45:13.925 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-15 21:45:13.981 DMR Slot 2, JitterBuffer: no data available, elapsed=1740ms, raw=31, head=31
D: 2018-01-15 21:45:13.982 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-15 21:45:14.043 DMR Slot 2, JitterBuffer: no data available, elapsed=1802ms, raw=32, head=32
D: 2018-01-15 21:45:14.043 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-15 21:45:14.105 DMR Slot 2, JitterBuffer: no data available, elapsed=1864ms, raw=33, head=33
D: 2018-01-15 21:45:14.106 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-15 21:45:14.162 DMR Slot 2, JitterBuffer: no data available, elapsed=1921ms, raw=34, head=34
D: 2018-01-15 21:45:14.162 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-15 21:45:14.224 DMR Slot 2, JitterBuffer: no data available, elapsed=1983ms, raw=35, head=35
D: 2018-01-15 21:45:14.224 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-15 21:45:14.281 DMR Slot 2, JitterBuffer: no data available, elapsed=2040ms, raw=36, head=36
D: 2018-01-15 21:45:14.281 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-15 21:45:14.343 DMR Slot 2, JitterBuffer: no data available, elapsed=2102ms, raw=37, head=37
D: 2018-01-15 21:45:14.343 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-15 21:45:14.404 DMR Slot 2, JitterBuffer: no data available, elapsed=2163ms, raw=38, head=38
D: 2018-01-15 21:45:14.405 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-15 21:45:14.461 DMR Slot 2, JitterBuffer: no data available, elapsed=2220ms, raw=39, head=39
D: 2018-01-15 21:45:14.461 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-15 21:45:14.523 DMR Slot 2, JitterBuffer: no data available, elapsed=2282ms, raw=40, head=40
D: 2018-01-15 21:45:14.523 DMR Slot 2, JitterBuffer: returning the last received frame
M: 2018-01-15 21:45:14.580 DMR Slot 2, network watchdog has expired

**Comment by pjao** [comment]
Also problems with XLX thru DMRGateway

M: 2018-01-15 21:53:02.365 DMR Slot 2, received RF voice header from CT2JAY to TG 6
D: 2018-01-15 21:53:02.486 DMR Slot 2, audio sequence no. 0, errs: 0/141 (0.0%)
D: 2018-01-15 21:53:02.545 DMR Slot 2, audio sequence no. 1, errs: 0/141 (0.0%)
D: 2018-01-15 21:53:02.605 DMR Slot 2, audio sequence no. 2, errs: 0/141 (0.0%)
D: 2018-01-15 21:53:02.665 DMR Slot 2, audio sequence no. 3, errs: 0/141 (0.0%)
D: 2018-01-15 21:53:02.725 DMR Slot 2, audio sequence no. 4, errs: 0/141 (0.0%)
D: 2018-01-15 21:53:02.787 DMR Slot 2, audio sequence no. 5, errs: 1/141 (0.7%)
D: 2018-01-15 21:53:02.850 DMR Slot 2, audio sequence no. 0, errs: 0/141 (0.0%)
D: 2018-01-15 21:53:02.907 DMR Slot 2, audio sequence no. 1, errs: 0/141 (0.0%)
D: 2018-01-15 21:53:02.965 DMR Slot 2, audio sequence no. 2, errs: 0/141 (0.0%)
D: 2018-01-15 21:53:03.027 DMR Slot 2, audio sequence no. 3, errs: 0/141 (0.0%)
D: 2018-01-15 21:53:03.085 DMR Slot 2, audio sequence no. 4, errs: 0/141 (0.0%)
D: 2018-01-15 21:53:03.147 DMR Slot 2, audio sequence no. 5, errs: 0/141 (0.0%)
D: 2018-01-15 21:53:03.205 DMR Slot 2, audio sequence no. 0, errs: 0/141 (0.0%)
D: 2018-01-15 21:53:03.267 DMR Slot 2, audio sequence no. 1, errs: 0/141 (0.0%)
D: 2018-01-15 21:53:03.325 DMR Slot 2, audio sequence no. 2, errs: 0/141 (0.0%)
D: 2018-01-15 21:53:03.385 DMR Slot 2, audio sequence no. 3, errs: 3/141 (2.1%)
D: 2018-01-15 21:53:03.445 DMR Slot 2, audio sequence no. 4, errs: 0/141 (0.0%)
D: 2018-01-15 21:53:03.507 DMR Slot 2, audio sequence no. 5, errs: 1/141 (0.7%)
M: 2018-01-15 21:53:03.565 DMR Slot 2, received RF end of voice transmission, 1.1 seconds, BER: 0.2%
D: 2018-01-15 21:53:03.745 DMR Slot 2, JitterBuffer: starting the timer
D: 2018-01-15 21:53:04.249 DMR Slot 2, JitterBuffer: no data available, elapsed=0ms, raw=0, head=0
D: 2018-01-15 21:53:04.255 DMR Slot 2, JitterBuffer: no data available, elapsed=6ms, raw=1, head=1
D: 2018-01-15 21:53:04.255 DMR Slot 2, JitterBuffer: no data available, elapsed=6ms, raw=2, head=2
D: 2018-01-15 21:53:04.312 DMR Slot 2, JitterBuffer: no data available, elapsed=63ms, raw=3, head=3
D: 2018-01-15 21:53:04.369 DMR Slot 2, JitterBuffer: no data available, elapsed=120ms, raw=4, head=4
D: 2018-01-15 21:53:04.431 DMR Slot 2, JitterBuffer: no data available, elapsed=182ms, raw=5, head=5
D: 2018-01-15 21:53:04.492 DMR Slot 2, JitterBuffer: no data available, elapsed=243ms, raw=6, head=6
D: 2018-01-15 21:53:04.549 DMR Slot 2, JitterBuffer: no data available, elapsed=300ms, raw=7, head=7
D: 2018-01-15 21:53:04.611 DMR Slot 2, JitterBuffer: no data available, elapsed=362ms, raw=8, head=8
D: 2018-01-15 21:53:04.673 DMR Slot 2, JitterBuffer: no data available, elapsed=424ms, raw=9, head=9
D: 2018-01-15 21:53:04.730 DMR Slot 2, JitterBuffer: no data available, elapsed=481ms, raw=10, head=10
D: 2018-01-15 21:53:04.791 DMR Slot 2, JitterBuffer: no data available, elapsed=542ms, raw=11, head=11
D: 2018-01-15 21:53:04.853 DMR Slot 2, JitterBuffer: no data available, elapsed=604ms, raw=12, head=12
D: 2018-01-15 21:53:04.910 DMR Slot 2, JitterBuffer: no data available, elapsed=661ms, raw=13, head=13
D: 2018-01-15 21:53:04.971 DMR Slot 2, JitterBuffer: no data available, elapsed=722ms, raw=14, head=14
D: 2018-01-15 21:53:05.033 DMR Slot 2, JitterBuffer: no data available, elapsed=784ms, raw=15, head=15
D: 2018-01-15 21:53:05.090 DMR Slot 2, JitterBuffer: no data available, elapsed=841ms, raw=16, head=16
D: 2018-01-15 21:53:05.213 DMR Slot 2, JitterBuffer: no data available, elapsed=964ms, raw=18, head=18
D: 2018-01-15 21:53:05.213 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-15 21:53:05.270 DMR Slot 2, JitterBuffer: no data available, elapsed=1021ms, raw=19, head=19
D: 2018-01-15 21:53:05.270 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-15 21:53:05.331 DMR Slot 2, JitterBuffer: no data available, elapsed=1082ms, raw=20, head=20
D: 2018-01-15 21:53:05.332 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-15 21:53:05.393 DMR Slot 2, JitterBuffer: no data available, elapsed=1144ms, raw=21, head=21
D: 2018-01-15 21:53:05.393 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-15 21:53:05.450 DMR Slot 2, JitterBuffer: no data available, elapsed=1201ms, raw=22, head=22
D: 2018-01-15 21:53:05.450 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-15 21:53:05.512 DMR Slot 2, JitterBuffer: no data available, elapsed=1263ms, raw=23, head=23
D: 2018-01-15 21:53:05.512 DMR Slot 2, JitterBuffer: returning the last received frame
M: 2018-01-15 21:53:05.513 DMR Slot 2, received network late entry from CT2JAY to TG 6
D: 2018-01-15 21:53:05.570 DMR Slot 2, JitterBuffer: no data available, elapsed=1321ms, raw=24, head=24
D: 2018-01-15 21:53:05.571 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-15 21:53:05.633 DMR Slot 2, JitterBuffer: no data available, elapsed=1384ms, raw=25, head=25
D: 2018-01-15 21:53:05.634 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-15 21:53:05.691 DMR Slot 2, JitterBuffer: no data available, elapsed=1442ms, raw=26, head=26
D: 2018-01-15 21:53:05.691 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-15 21:53:05.753 DMR Slot 2, JitterBuffer: no data available, elapsed=1504ms, raw=27, head=27
D: 2018-01-15 21:53:05.753 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-15 21:53:05.811 DMR Slot 2, JitterBuffer: no data available, elapsed=1562ms, raw=28, head=28
D: 2018-01-15 21:53:05.811 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-15 21:53:05.873 DMR Slot 2, JitterBuffer: no data available, elapsed=1624ms, raw=29, head=29
D: 2018-01-15 21:53:05.873 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-15 21:53:05.931 DMR Slot 2, JitterBuffer: no data available, elapsed=1682ms, raw=30, head=30
D: 2018-01-15 21:53:05.931 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-15 21:53:05.993 DMR Slot 2, JitterBuffer: no data available, elapsed=1744ms, raw=31, head=31
D: 2018-01-15 21:53:05.993 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-15 21:53:06.050 DMR Slot 2, JitterBuffer: no data available, elapsed=1801ms, raw=32, head=32
D: 2018-01-15 21:53:06.051 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-15 21:53:06.113 DMR Slot 2, JitterBuffer: no data available, elapsed=1864ms, raw=33, head=33
D: 2018-01-15 21:53:06.113 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-15 21:53:06.170 DMR Slot 2, JitterBuffer: no data available, elapsed=1921ms, raw=34, head=34
D: 2018-01-15 21:53:06.171 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-15 21:53:06.233 DMR Slot 2, JitterBuffer: no data available, elapsed=1984ms, raw=35, head=35
D: 2018-01-15 21:53:06.233 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-15 21:53:06.290 DMR Slot 2, JitterBuffer: no data available, elapsed=2041ms, raw=36, head=36
D: 2018-01-15 21:53:06.291 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-15 21:53:06.353 DMR Slot 2, JitterBuffer: no data available, elapsed=2104ms, raw=37, head=37
D: 2018-01-15 21:53:06.353 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-15 21:53:06.410 DMR Slot 2, JitterBuffer: no data available, elapsed=2161ms, raw=38, head=38
D: 2018-01-15 21:53:06.411 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-15 21:53:06.473 DMR Slot 2, JitterBuffer: no data available, elapsed=2224ms, raw=39, head=39
D: 2018-01-15 21:53:06.473 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-15 21:53:06.530 DMR Slot 2, JitterBuffer: no data available, elapsed=2281ms, raw=40, head=40
D: 2018-01-15 21:53:06.530 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-15 21:53:06.593 DMR Slot 2, JitterBuffer: no data available, elapsed=2344ms, raw=41, head=41
D: 2018-01-15 21:53:06.593 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-15 21:53:06.650 DMR Slot 2, JitterBuffer: no data available, elapsed=2401ms, raw=42, head=42
D: 2018-01-15 21:53:06.651 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-15 21:53:06.713 DMR Slot 2, JitterBuffer: no data available, elapsed=2464ms, raw=43, head=43
D: 2018-01-15 21:53:06.713 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-15 21:53:06.770 DMR Slot 2, JitterBuffer: no data available, elapsed=2521ms, raw=44, head=44
D: 2018-01-15 21:53:06.770 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-15 21:53:06.833 DMR Slot 2, JitterBuffer: no data available, elapsed=2584ms, raw=45, head=45
D: 2018-01-15 21:53:06.833 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-15 21:53:06.890 DMR Slot 2, JitterBuffer: no data available, elapsed=2641ms, raw=46, head=46
D: 2018-01-15 21:53:06.891 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-15 21:53:06.953 DMR Slot 2, JitterBuffer: no data available, elapsed=2704ms, raw=47, head=47
D: 2018-01-15 21:53:06.953 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-01-15 21:53:07.010 DMR Slot 2, JitterBuffer: no data available, elapsed=2761ms, raw=48, head=48
D: 2018-01-15 21:53:07.010 DMR Slot 2, JitterBuffer: returning the last received frame
M: 2018-01-15 21:53:07.011 DMR Slot 2, network watchdog has expired, 1.6 seconds, 96% packet loss, BER: 0.0%

**Comment by pjao** [comment]
After some more tests it looks like it's working.

Somehow more difficult to receive, but it looks fine now.

**Comment by stefansaraev** [comment]
confirmed. sometimes I do still get "received network late entry / watchdog has expired" in the log and then private call follows right after SMS was received, but that's very rare
